import csv
from pathlib import Path


BASE = Path("projects/ROX2-Z3SL4/02-boq")

VALUE_FIXES = {
    "?? r?i": "Đồ rời",
    "??n & MEP (m? r?ng)": "Đèn & MEP (mở rộng)",
    "Ho?n thi?n t??ng, ?? li?n t??ng": "Hoàn thiện tường, đồ liền tường",
    "Ho?n thi?n th? (m? r?ng)": "Hoàn thiện thô (mở rộng)",
    "N?i th?t tr?ng tr?": "Nội thất trang trí",
    "Nội thất tr?ng trí": "Nội thất trang trí",
    "Thi?t b? v? sinh": "Thiết bị vệ sinh",
    "? c?m/c?ng t?c": "Ổ cắm/công tắc",
    "? c?m/c?ng t?c b?p": "Ổ cắm/công tắc bếp",
    "? c?m/c?ng t?c k? thu?t": "Ổ cắm/công tắc kỹ thuật",
    "??n k? thu?t": "Đèn kỹ thuật",
    "??n tr?n gara": "Đèn trần gara",
    "??n tr?n v? ??n tr?ng tr?": "Đèn trần và đèn trang trí",
    "??n v? ? c?m WC": "Đèn và ổ cắm WC",
    "??n v? ? c?m WC1": "Đèn và ổ cắm WC1",
    "??n v? ? c?m WC3": "Đèn và ổ cắm WC3",
    "??n v? ? c?m WC4": "Đèn và ổ cắm WC4",
    "??n v? ? c?m master": "Đèn và ổ cắm master",
    "??n v? ? c?m ph?ng ng? 1": "Đèn và ổ cắm phòng ngủ 1",
    "??n v? ? c?m ph?ng ng? 2": "Đèn và ổ cắm phòng ngủ 2",
    "??n v? ? c?m powder": "Đèn và ổ cắm powder",
    "??n v? ? c?m s?n ph?i": "Đèn và ổ cắm sân phơi",
    "??n v? ? c?m th? vi?n": "Đèn và ổ cắm thư viện",
    "??n v? ? c?m workshop": "Đèn và ổ cắm workshop",
    "?p/l?t WC1": "Ốp/lát WC1",
    "?p/l?t WC3": "Ốp/lát WC3",
    "?p/l?t WC4": "Ốp/lát WC4",
    "?p/l?t g?ch WC": "Ốp/lát gạch WC",
    "?p/l?t powder": "Ốp/lát powder",
    "?p/s?n t??ng s?n ph?i": "Ốp/sơn tường sân phơi",
    "B?n ??o b?p": "Bàn đảo bếp",
    "B?n ?n": "Bàn ăn",
    "B?n c?u": "Bồn cầu",
    "B?n console": "Bàn console",
    "B?n l?m vi?c": "Bàn làm việc",
    "B?n nh?": "Bàn nhỏ",
    "B?n t?m n?m": "Bồn tắm nằm",
    "B?n tr?n": "Bàn tròn",
    "B?n tr?ng ?i?m": "Bàn trang điểm",
    "G??ng/ph? ki?n WC": "Gương/phụ kiện WC",
    "G??ng/ph? ki?n powder": "Gương/phụ kiện powder",
    "Gh? ?n": "Ghế ăn",
    "Gh? b?nh": "Ghế bành",
    "Gh? l?m vi?c": "Ghế làm việc",
    "Gh? nh?": "Ghế nhỏ",
    "Gh? ph?": "Ghế phụ",
    "Gh? tr?ng ?i?m": "Ghế trang điểm",
    "Gh? tr?ng ?i?m/ph?": "Ghế trang điểm/phụ",
    "Gi??ng ng?": "Giường ngủ",
    "Gương/kính tr?ng trí ốp tường": "Gương/kính trang trí ốp tường",
    "K? tr?ng tr?": "Kệ trang trí",
    "L?t s?n g?ch": "Lát sàn gạch",
    "L?t s?n gara": "Lát sàn gara",
    "L?t s?n kh? + ph?ng k? thu?t": "Lát sàn kho + phòng kỹ thuật",
    "L?t s?n master": "Lát sàn master",
    "L?t s?n ph?ng ng? 1": "Lát sàn phòng ngủ 1",
    "L?t s?n ph?ng ng? 2": "Lát sàn phòng ngủ 2",
    "L?t s?n s?n ph?i": "Lát sàn sân phơi",
    "L?t s?n th? vi?n": "Lát sàn thư viện",
    "L?t s?n workshop": "Lát sàn workshop",
    "Lavab? + v?i": "Lavabo + vòi",
    "Nẹp kim loại tr?ng trí": "Nẹp kim loại trang trí",
    "R?m cu?n": "Rèm cuốn",
    "R?m v?i 1 l?p": "Rèm vải 1 lớp",
    "R?m v?i 2 l?p": "Rèm vải 2 lớp",
    "S?n/ho?n thi?n t??ng": "Sơn/hoàn thiện tường",
    "Sen t?m/ph? ki?n": "Sen tắm/phụ kiện",
    "T? ??u gi??ng": "Tủ đầu giường",
    "T? b?p ??t/outdoor": "Tủ bếp ướt/outdoor",
    "T? b?p kh?": "Tủ bếp khô",
    "T? gi?t s?y": "Tủ giặt sấy",
    "T? qu?n ?o": "Tủ quần áo",
    "T? tivi": "Tủ tivi",
    "T?/k? lavab?": "Tủ/kệ lavabo",
    "Th?m": "Thảm",
    "Th?m khu ?n": "Thảm khu ăn",
    "Tr?n ho?n thi?n": "Trần hoàn thiện",
    "Tr?n th?ch cao/s?n": "Trần thạch cao/sơn",
    "Tr?n/s?n ho?n thi?n": "Trần/sơn hoàn thiện",
    "Đèn thả tr?ng trí": "Đèn thả trang trí",
    "Đồ tr?ng trí (art decor)": "Đồ trang trí (art decor)",
    "? c?m ??i + USB + c?ng t?c + h?p ??u ch?": "Ổ cắm đôi + USB + công tắc + hộp đầu chờ",
    "? c?m ??i/c?ng t?c theo MBOC_01": "Ổ cắm đôi/công tắc theo MBOC_01",
    "??n am tr?n/??n tha/LED theo MBTBTRAN_01": "Đèn âm trần/đèn thả/LED theo MBTBTRAN_01",
    "??n g?n n?i/h? chi?u s?ng theo MBTBTRAN_01": "Đèn gắn nổi/hố chiếu sáng theo MBTBTRAN_01",
    "CA-2.01 hoac t? lavab?": "CA-2.01 hoặc tủ lavabo",
    "CH-1.01, gh? an khu b?n an": "CH-1.01, ghế ăn khu bàn ăn",
    "CP-01 th?m ph?ng giai tri - MBLS_01": "CP-01 thảm phòng giải trí - MBLS_01",
    "PT-04 khe/tr?n khac cao ?? + SF-01, MBTRAN_01": "PT-04 khe/trần khác cao độ + SF-01, MBTRAN_01",
    "UC-02 giay dan t??ng + WD-01 chan t??ng MDF, MDDT_03": "UC-02 giấy dán tường + WD-01 chân tường MDF, MDDT_03",
    "WDP/WD-01 g? MDF ch?ng ?m dien t??ng ph?ng giai tri": "WDP/WD-01 gỗ MDF chống ẩm diện tường phòng giải trí",
    "di?n t?ch ph?ng": "diện tích phòng",
    "di?n t?ch s?n ph?i": "diện tích sân phơi",
    "di?n t?ch t?m t?nh theo c?u h?nh": "diện tích tạm tính theo cấu hình",
    "g??ng va ph? ki?n co b?n": "gương và phụ kiện cơ bản",
    "kh? + ph?ng k? thu?t": "kho + phòng kỹ thuật",
    "khu b?p + an": "khu bếp + ăn",
    "khu b?p + kitchen outdoor": "khu bếp + bếp ngoài trời",
    "khu b?p/an": "khu bếp/ăn",
    "panel tr?ng trí hoa văn tia - MDDT_07": "panel trang trí hoa văn tia - MDDT_07",
    "ph?ng ng? 1": "phòng ngủ 1",
    "ph?ng ng? 2": "phòng ngủ 2",
    "ph?ng th? vi?n": "phòng thư viện",
    "san + t??ng": "sàn + tường",
    "san + t??ng WC": "sàn + tường WC",
    "san gara tang ham, di?n t?ch ph?ng": "sàn gara tầng hầm, diện tích phòng",
    "theo MB thiet bi tr?n/? c?m": "theo MB thiết bị trần/ổ cắm",
    "theo mat b?ng ? c?m MBOC_01": "theo mặt bằng ổ cắm MBOC_01",
    "theo mat b?ng thiet bi tr?n MBTBTRAN_01": "theo mặt bằng thiết bị trần MBTBTRAN_01",
    "b?": "bộ",
    "c?i": "cái",
    "th?p": "thấp",
    "trung b?nh": "trung bình",
}

TEXT_FIXES = {
    "2 b?n giuong - c?n m?t ??ng": "2 bên giường - cần mặt đứng",
    "2 b?n giuong - c?n m?t ??ng de b?c chi ti?t": "2 bên giường - cần mặt đứng để bóc chi tiết",
    "2 b?n giuong master - c?n m?t ??ng": "2 bên giường master - cần mặt đứng",
    "2 gh? khu master/WC4 theo MBNT_04 - c?n x?c nh?n v? tr?": "2 ghế khu master/WC4 theo MBNT_04 - cần xác nhận vị trí",
    "2 v? tr? r?m vai khu b?p/an": "2 vị trí rèm vải khu bếp/ăn",
    "??c theo 2 cum th?m master": "Ước theo 2 cụm thảm master",
    "??c theo cum b?n an": "Ước theo cụm bàn ăn",
    "??c theo cum b?n l?m vi?c": "Ước theo cụm bàn làm việc",
    "??c theo cum giuong": "Ước theo cụm giường",
    "??m tren MBNT_02": "Đếm trên MBNT_02",
    "B?n phu gan khu an - MBNT_02": "Bàn phụ gần khu ăn - MBNT_02",
    "B?p ngo?i tr?i 5.5m2 - MBNT_02": "Bếp ngoài trời 5.5m2 - MBNT_02",
    "C?a s? ph?ng ng? 1": "Cửa sổ phòng ngủ 1",
    "C?n ??i chi?u b?n ve TBVS": "Cần đối chiếu bản vẽ TBVS",
    "C?n m?t ??ng WC": "Cần mặt đứng WC",
    "C?n m?t ??ng/chi ti?t ?? g? de b?c md/m2": "Cần mặt đứng/chi tiết đồ gỗ để bóc md/m2",
    "Chua b?c chi ti?t": "Chưa bóc chi tiết",
    "Chua b?c chi ti?t - doc MB ? c?m": "Chưa bóc chi tiết - đọc MB ổ cắm",
    "Chua b?c chi ti?t - doc MB thiet bi tr?n": "Chưa bóc chi tiết - đọc MB thiết bị trần",
    "Chua b?c chi ti?t tr?n": "Chưa bóc chi tiết trần",
    "Chua b?c chi ti?t tr?n - doc tr?ng 15-20": "Chưa bóc chi tiết trần - đọc trang 15-20",
    "Cua/khung ngoai khu b?p": "Cửa/khung ngoài khu bếp",
    "Di?n t?ch san 14m2; t??ng c?n b?c chi ti?t": "Diện tích sàn 14m2; tường cần bóc chi tiết",
    "Di?n t?ch san 7.5m2; t??ng c?n b?c chi ti?t": "Diện tích sàn 7.5m2; tường cần bóc chi tiết",
    "Di?n t?ch san theo MBNT_01; t??ng c?n b?c theo m?t ??ng/ho?n thi?n": "Diện tích sàn theo MBNT_01; tường cần bóc theo mặt đứng/hoàn thiện",
    "Di?n t?ch san theo MBNT_02; t??ng c?n b?c chi ti?t": "Diện tích sàn theo MBNT_02; tường cần bóc chi tiết",
    "Doc tr?ng 10 MBLS_01; l?y theo di?n t?ch ph?ng 32m2": "Đọc trang 10 MBLS_01; lấy theo diện tích phòng 32m2",
    "Doc tr?ng 16 MBTRAN_01; l?y theo di?n t?ch ph?ng": "Đọc trang 16 MBTRAN_01; lấy theo diện tích phòng",
    "Doc tr?ng 22; ??m 1 diem P.K? thu?t + 1 diem Kho": "Đọc trang 22; đếm 1 điểm P.Kỹ thuật + 1 điểm Kho",
    "Doc tr?ng 22; ??m so b? 4 diem ??n trong khu gara": "Đọc trang 22; đếm sơ bộ 4 điểm đèn trong khu gara",
    "Doc tr?ng 22; ??m so b? cac diem ??n khu P.Giai tri": "Đọc trang 22; đếm sơ bộ các điểm đèn khu P.Giải trí",
    "Doc tr?ng 28 MBOC_01; ??m cac v? tr? trong P.Giai tri": "Đọc trang 28 MBOC_01; đếm các vị trí trong P.Giải trí",
    "Doc tr?ng 28; ??m v? tr? ? c?m/c?ng t?c khu gara": "Đọc trang 28; đếm vị trí ổ cắm/công tắc khu gara",
    "Doc tr?ng 28; ??m v? tr? ? c?m/c?ng t?c trong kh? + P.K? thu?t": "Đọc trang 28; đếm vị trí ổ cắm/công tắc trong kho + P.Kỹ thuật",
    "Doc tr?ng 34 MBHTT_01 + tr?ng 40-41 MDDT_01/02; t?nh so b? dien op go cac m?t ??ng": "Đọc trang 34 MBHTT_01 + trang 40-41 MDDT_01/02; tính sơ bộ diện ốp gỗ các mặt đứng",
    "Doc tr?ng 38 MBHTT_05; t?nh so b? chu vi khu s?n ph?i x cao trung b?nh 2.0m": "Đọc trang 38 MBHTT_05; tính sơ bộ chu vi khu sân phơi x cao trung bình 2.0m",
    "Doc tr?ng 42 MDDT_03; 2 dien t??ng ch?nh 5.72x2.4 + 4.174x2.4 tr? chan t??ng": "Đọc trang 42 MDDT_03; 2 diện tường chính 5.72x2.4 + 4.174x2.4 trừ chân tường",
    "Ky hi?u n?m gan khu WC1/b?n tr?ng diem tren MBNT_03; c?n x?c nh?n scope": "Ký hiệu nằm gần khu WC1/bàn trang điểm trên MBNT_03; cần xác nhận scope",
    "Logia/cua b?n ph?ng": "Logia/cửa bên phòng",
    "MBNT_01 ghi P.K? thu?t 5.8m2 + kh? 4.2/4.4m2": "MBNT_01 ghi P.Kỹ thuật 5.8m2 + kho 4.2/4.4m2",
    "MBNT_03 - c?n m?t ??ng/chi ti?t ?? g?": "MBNT_03 - cần mặt đứng/chi tiết đồ gỗ",
    "MBNT_04 co 2 chau lavab?": "MBNT_04 có 2 chậu lavabo",
    "Mảng kính/gương lớn tường thông tầng - CẦN xác nhận kính tr?ng trí hay cửa kính KT (có thể tách khỏi scope nội thất)": "Mảng kính/gương lớn tường thông tầng - CẦN xác nhận kính trang trí hay cửa kính KT (có thể tách khỏi scope nội thất)",
    "T?m t?nh": "Tạm tính",
    "T?m t?nh theo WC 4m2": "Tạm tính theo WC 4m2",
    "Thay tren MBNT_01 - c?n ??i chi?u b?n ve TBVS": "Thấy trên MBNT_01 - cần đối chiếu bản vẽ TBVS",
    "Theo MBNT_01: Gara 50m2; vat lieu/doc san doc theo tr?ng l?t s?n": "Theo MBNT_01: Gara 50m2; vật liệu/sàn đọc theo trang lát sàn",
    "Theo c?u h?nh": "Theo cấu hình",
    "Theo di?n t?ch c?u h?nh; vat lieu doc tr?ng l?t s?n": "Theo diện tích cấu hình; vật liệu đọc trang lát sàn",
}


def fix(value):
    if value is None:
        return value
    value = VALUE_FIXES.get(value, value)
    return TEXT_FIXES.get(value, value)


def main():
    for path in sorted(BASE.glob("*.csv")):
        with path.open(encoding="utf-8-sig", newline="") as f:
            reader = csv.DictReader(f)
            fieldnames = reader.fieldnames
            rows = [{k: fix(v) for k, v in row.items()} for row in reader]
        with path.open("w", encoding="utf-8-sig", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames, lineterminator="\n")
            writer.writeheader()
            writer.writerows(rows)


if __name__ == "__main__":
    main()
